name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4
      - run: gradle build --no-daemon
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: meta-fields/build/libs/
