name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  assemble:
    environment: OSSRH
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4
      - name: assemble
        run: gradle build sign --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: meta-fields/build/libs/
