name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
      - run: gradle build --no-daemon
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: meta-fields/build/libs/
