name: CI
on:
  push:
    branches:
      - main
      - build_test
  pull_request:
    branches:
      - main

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
      - run: gradle build --no-daemon
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: meta-fields/build/libs/

  publish:
    name: Publish release
    needs: assemble
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
      - name: Publish to GitHub Packages
        run: |
          echo "Publishing to GitHub Packages"
          gradle build --no-daemon

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
